version: "3.7"
services:
  homeassistant:
    container_name: home-assistant
    image: homeassistant/home-assistant
    volumes:
      - ${HOMEASSISTANT_BASE_PATH}/ssh_config/:/root/.ssh
      - ${HOMEASSISTANT_BASE_PATH}/volumes/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock
    restart: unless-stopped
    network_mode: host
    depends_on:
      - mariadb
      - mosquitto
      - influxdb

  mariadb:
    image: mariadb:11
    container_name: mariadb
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: "${MYSQL_ROOT_PASSWORD}"
      MYSQL_DATABASE: ha_db
      MYSQL_USER: homeassistant
      MYSQL_PASSWORD: "${HA_MYSQL_PASSWORD}"
    volumes:
      - ${HOMEASSISTANT_BASE_PATH}/volumes/maria_db:/var/lib/mysql
    ports:
      - "3306:3306"

  influxdb:
    image: influxdb:1.8
    restart: unless-stopped
    ports:
      - "8086:8086"
    volumes:
      - ${HOMEASSISTANT_BASE_PATH}/volumes/influxdb:/var/lib/influxdb
    environment:
      - INFLUXDB_DB=db0
      - INFLUXDB_ADMIN_USER=${INFLUXDB_USERNAME}
      - INFLUXDB_ADMIN_PASSWORD=${INFLUXDB_PASSWORD}

  mosquitto:
    image: eclipse-mosquitto
    restart: unless-stopped
    hostname: mosquitto
    container_name: mosquitto
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - ${HOMEASSISTANT_BASE_PATH}/volumes/mosquitto/config:/mosquitto/config


  esphome:
    container_name: esphome
    image: esphome/esphome:latest
    environment:
      - TZ=Europe/Amsterdam
    network_mode: host
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${HOMEASSISTANT_BASE_PATH}/volumes/homeassistant/esphome:/config:rw
    depends_on:
      - mosquitto

  zigbee2mqtt:
    container_name: zigbee2mqtt
    image: koenkk/zigbee2mqtt
    volumes:
      - ${HOMEASSISTANT_BASE_PATH}/volumes/homeassistant/zigbee2mqtt:/app/data
      - /run/udev:/run/udev:ro
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    restart: always
    network_mode: host
    privileged: true
    environment:
      - TZ=Europe/Amsterdam
    depends_on:
      - mosquitto

  nginx:
    image: nginx:latest
    container_name: home-assistant_nginx
    ports:
      - "443:443"
    volumes:
      - ./nginx.template.conf:/etc/nginx/nginx.template.conf:rw
      - ./certificates:/etc/nginx/certs:ro
    restart: unless-stopped
    depends_on:
      - homeassistant
    environment:
      - DOMAIN=${DUCKDNS_DOMAIN}
      - SERVER_ADDR=${HASS_SERVER_ADDR}
      - SSL_PORT=${SSL_PORT}
    command: |
      /bin/bash -c "envsubst '$${DOMAIN} $${SERVER_ADDR} $${SSL_PORT}' < /etc/nginx/nginx.template.conf > /etc/nginx/nginx.conf && exec nginx -g 'daemon off;'"

